--- # CONDITIONS PLAYBOOK
- hosts: DEMO
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install apache on debian
      command: apt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: insatll apache on redhat
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
