--- # my loops playbook
- hosts: DEMO
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: add a list of user
      user: name='{{item}}' state=present
      with_items:
              - Bhupinder
              - vivek
              - arnav
              - ayush
              - sanjeev
           
